# Site
title:                Nwangele Post
description:         From Nwangele to the world
logo:                 'assets/img/favicon/logo.png'
baseurl:              "/np-site/"
url:                  ""


image-path:          "assets/images/uploads"
default_width:       "1200"
sizes:               "(min-width: 64em) 220x, (min-width: 48em) 150px, 125px"
data-srcset:
  - 300
  - 750
  - 1000


livereload: false

# Jekyll
permalink:            pretty
markdown:             kramdown
sass:
  sass_dir:           _sass
  style:              compressed

#comments

collections:
   feature-cover:
    output: true
   opinion:
    output: true
   gallery:
    output: true



plugins:
  - jekyll-paginate-v2
  - jekyll-feed
  - jekyll-timeago

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate-v2
  - jekyll_picture_tag
  - jekyll-tagging-related_posts
  - jekyll-timeago


jekyll_timeago:
  depth: 1

jekyll-mentions:
    base_url: https://github.com



# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]


include: ["_pages"]

pagination:

  enabled: true
  debug: false
  # The default document collection to paginate if nothing is specified ('posts' is default)
  collection: 'posts'
  per_page: 5
  permalink: '/page/:num/' 
  # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  category: 'posts'
  tag: ''
  locale: '' 
  trail: 
    before: 2
    after: 2
  extension: html
  indexpage: 'index'
############################################################
autopages:
  enabled: true
  categories: 
    enabled: false
  collections:
    enabled: false
  tags:
    enabled: true
    layouts:
      - "autopage_tags.html"
    path: "/tag/:tag"

picture:
  ignore_missing_images: [development, testing]
  disabled: true

