# Site
title:                Nwangele Post
deescription:         From Nwangele to the world
logo:                 'assets/img/logo.png'
#baseurl:               /nwangelepost


# Jekyll
permalink:            pretty
markdown:             kramdown
sass:
  sass_dir:           _sass
  style:              compressed

#comments

# Social

plugins:
  - jekyll-gallery-generator

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  -jekyll-gallery-generator

jekyll-mentions:
    base_url: https://github.com

gallery:
  dir: C:\Users\Andre\Documents\Workspace\2020 PROJECTS\DEV_BLOCK\Nwangele Post\site\assets\images\uploads\gallery               # Path to the gallery
  symlink: false            # false: copy images into _site. true: create symbolic links (saves disk space)
  title: "Photos"           # Title for gallery index page
  title_prefix: "Photos: "  # Title prefix for gallery pages. Gallery title = title_prefix + gallery_name
  sort_field: "date_time"   # How to sort galleries on the index page.
                            # Possible values are: title, date_time, best_image
  thumbnail_size:
    x: 200px                  # max width of thumbnails (in pixels)
    y: 200px                  # max height of thumbnails (in pixels)

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]