# Site
title:                Nwangele Post
deescription:         From Nwangele to the world
logo:                 'assets/img/logo.png'


# Jekyll
permalink:            /:title/
markdown:             kramdown
sass:
  sass_dir:           _sass
  style:              compressed

#comments

# Social

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]